### ISSUE TITLE
[feature] all in one yaml file 

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#1098]
When I managed the terraform codes, terragrunt gives big help and make the task easy at project mode. But when start supporting these instruction as code, it is hard to manage  multiple accounts easily, to get upgraded,especially the more than 50+ aws accounts in your lilst. 

Because the file `terraform.hcl` are everywhere. 

Could we have a single of truth to save all details in one file, such as a `manifest.yaml`

It could be like this: 

```
cat manifest.yaml

_global: 
   key: value
account-1:
  dev:
    us-east-2
      vpc: 
         module: xxx
         version: xxxx
         variables: 
            cidr: xxx
           private_subnets: xxxx
       ecs:
         module: xxx
         version: xxxx
account-2:
  sit:
    us-east-2
      vpc: 
         module: xxx
         version: xxxx
         variables: 
            cidr: xxx
           private_subnets: xxxx
       eks:
         module: xxx
         version: xxxx
```

It will be better to support `${local.variable}` in it.
