### ISSUE TITLE
Using dependencies and locals with yamldecoded input

### ISSUE THREAD

**Issue by bankinobi** [gruntwork-io/terragrunt#1252]
Is there any way i can use dependencies and locals in my yaml var files? 
Like this one:
```
dns_zones:
  - name: "test-com"
    dns_name: "test.com."
    visibility: "puclic"
    private_visibility_config:
      [
        'dependency.networks.outputs.network_selflink["default"]'
      ]
```
In this condition `private_visibility_config` passed as is, without replacing dependency expression.

**Comment by yorinasub17** [comment]
Does it work if you use [templatefile](https://www.terraform.io/docs/configuration/functions/templatefile.html)? E.g.,

**yaml file**
```yaml
dns_zones:
  - name: "test-com"
    dns_name: "test.com."
    visibility: "puclic"
    private_visibility_config:
      [
        '${private_visibility_config}'
      ]
```

**terragrunt.hcl**
```hcl
inputs = yamldecode(templatefile("path/to/yaml", { private_visibility_config = dependency.networks.outputs.network_selflink["default"] }))
```
