### ISSUE TITLE
Error: Error building ARM Config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1

### ISSUE THREAD

**Issue by judaondo** [gruntwork-io/terragrunt#1447]
Hello I have this `terragrunt.hcl` file on the root on the project and when applying `terragrunt plan-all` it goes to all .cache folders.

This provider logs in in into azure using Service Principal (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret). 

```
remote_state {
  backend = "azurerm"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    resource_group_name  = "dev-remote-state"
    storage_account_name = "devterraform"
    container_name       = "tfstate"
    key                  = "${path_relative_to_include()}/terraform.tfstate"
  }
}

generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
# Configure Terraform
terraform {
  required_version = "= 0.13.5"
}

# Configure the Azure Provider
provider "azurerm" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "= 2.38.0"
  # Create a file "secrets.tfvars" with the following fields. More info here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
  subscription_id = "00000000-0000-0000-00000000"
  client_id            = "00000000-0000-0000-00000000" 
  client_secret     = "password"
  tenant_id          = "00000000-0000-0000-00000000"
  features {}
}
EOF
}
```

But when applying it I get the following error: 

```
Initializing the backend...

Error: Error building ARM Config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1



[terragrunt] 2020/11/27 15:04:22 Encountered the following errors:
Hit multiple errors:
exit status 1
```

If I place the provider inside Terraform it works fine. 

Am I missing something??

Terraform version: v0.13.5
Terragrunt version: v0.26.4

**Comment by brikis98** [comment]
Terragrunt doesn't do anything directly related to Azure AFAIK, so this seems like a Terraform / Azure issue, and not a Terragrunt one. Note that since you're using `generator` to  generate  code, you can go into `.terragrunt-cache/.../<YOUR MODULE>` and run `terraform` commands directly in that folder to take Terragrunt completely out of the equation.

**Comment by Sampy84** [comment]
Hi @judaondo,
I had also encountered this error message:
**Error: Error building ARM Config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1**

and can confirm that it does not depend on Terragrunt.
I solved it this way:

1. Upgraded terraform (0.14.3) and Terragrunt (0.26.7)
2. Updated azure-cli to the latest version
3. I logged in as follows: az login -u _username_ -p _pwd_.

In my case, it was just an authentication problem.
I think it was because Terragrunt was not able to decipher the authentication failed message that was displayed correctly by terraform.
To test this, go to the folder mentioned by @brikis98 and run a terraform plan directly and then check the message you obtain.

**Comment by abhinaba-chakraborty-by** [comment]
@judaondo @Sampy84 

The below solution works:

terragrunt.hcl
```
generate "provider" {
  path      = "_provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF

provider "azurerm" {
  features {

  }
}

EOF
}

remote_state {
  backend = "azurerm"

  disable_init = tobool(get_env("TERRAGRUNT_DISABLE_INIT", "false"))

  generate = {
    path      = "_backend.tf"
    if_exists = "overwrite"
  }

  config = {
    resource_group_name  = "eso-sandbox-rg"
    storage_account_name = "esosbxtfbackend"
    container_name       = "tfstate"
    key                  = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```

And, my github workflow:
```
  sandbox-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: Sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 0.14.6
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.0.0
        with:
          terragrunt_version: 0.27.0
      - name: Export Azure Login Credentials
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
      - name: Create Execution Plan
        run: terragrunt plan-all
      - name: Apply Changes
        run: yes | terragrunt apply-all
```
