### ISSUE TITLE
Merge configuration from multiple terragrunt.hcl files

### ISSUE THREAD

**Issue by anry-m** [gruntwork-io/terragrunt#1516]
Hi all, 
I've tried to split input data from the terraform code using yaml, but faced with the issue. I can't split the terragrunt configuration into multiple files.

Here is my working layout but with lots of copy and paste. 
```
env1
    terragrunt.hcl // root configuration. generate providers.tf and remote_state.tf
    - route53
        terragrunt.hcl // vpc dependency, route53 module, inputs
    - vpc
        terragrunt.hcl // vpc_module, inputs
    - applications
        - app1
            services.yaml
            terragrunt.hcl // vpc dependency, route53 dependency, locals, inputs
        - app2
            services.yaml
            terragrunt.hcl // vpc dependency, route53 dependency, locals, inputs
        - app3
            services.yaml
            terragrunt.hcl // vpc dependency, route53 dependency, locals, inputs
env2
    ...
```
Each services.yaml contains next properties description

```
services:
    "<service-name-1>":
        ami_id: <ami_id>
        iam_role: <iam_role>
        instnace_count: <count>
        tags: <tags>
    "<service-name-2>":
        ami_id: <ami_id>
        iam_role: <iam_role>
        instnace_count: <count>
        tags: <tags>
    ...
```

Each terragrunt.hcl inside the applications folder contains a similar configuration with defined dependencies, locals, and inputs and uses the same _deploy_vm_ module.
I want to have flexibility in versioning so each terragrunt.hcl could contain terraform block with the exact version
```
terraform {
    source = "<path_to_module>//deploy_vm?ref=some_version"
}
```

I'd like to keep configuration DRY. Ideally I'd like to have only terraform block with version in each terragrunt.hcl and the rest configuration in another terragrunt file.

```
    terragrunt.hcl // root configuration. generate providers.tf and remote_state.tf
    - applications
        terragrunt.hcl  // dependencies, inputs, locals
        - app1
            services.yaml
            terragrunt.hcl // specific version of terraform module
        - app2
            services.yaml
            terragrunt.hcl // specific version of terraform module
        - app3
            services.yaml
            terragrunt.hcl // specific version of terraform module
```
The problem is I can't merge the configuration of multiple terragrunt files using the "include" statement. 
Is it possible in the nearest future? Are there workarounds?
