### ISSUE TITLE
Using `sops_decrypt_file()` in ternaries always attempts to connect to Azure Key Vault

### ISSUE THREAD

**Issue by MHarutunian** [gruntwork-io/terragrunt#2172]
Using `sops_decrypt_file()` in a ternary seems to always attempt to connect to the respective Azure Key Vault, regardless of the conditional's outcome.

Minimal example:
```
locals {
  filename       = "input.enc.yml"
  is_restricted  = tobool(get_env("IS_RESTRICTED", "false"))
  decrypted_file = local.is_restricted ? file(local.filename) : sops_decrypt_file(local.filename)
}

inputs = yamldecode(local.decrypted_file)
```
Running `IS_RESTRICTED=1 terragrunt apply` (also `init`/`plan`/...) will use `file(local.filename)` as expected, but without the required Key Vault permissions `sops_decrypt_file()` will still be called and print the following errors:
```
[AZKV]	 ERRO[0000] Failed to create Azure authorizer             error="Invoking Azure CLI failed with the following error: ERROR: Please run 'az login' to setup account.\n"
[AZKV]	 ERRO[0000] Failed to create Azure authorizer             error="Invoking Azure CLI failed with the following error: ERROR: Please run 'az login' to setup account.\n"
[AZKV]	 ERRO[0000] Failed to create Azure authorizer             error="Invoking Azure CLI failed with the following error: ERROR: Please run 'az login' to setup account.\n"

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!
```
The command succeeds in the end, but the error logs are pretty irritating. Setting `IS_RESTRICTED` to `false` will print the same error message, but also fail the command entirely.

We use this setup in our terragrunt configuration files so we are able to run certain commands in restricted environments (similar to `disable_init`), e.g. in our CI/CD Pipelines for running `validate` across all environments. The pipelines do not fail, but our logs are spammed with error messages.

Side notes:
* I've only tested this with SOPS keys from Azure Key Vault, but I could imagine that it happens regardless of the encryption key used - after all `sops_decrypt_file()` does not know that Azure is in use until it attempts to decrypt the file
* This does not happen when using conditional syntax in for..in loops, like
```
decrypted_files = [
  for f in local.files : sops_decrypt_file(f) if !local.is_restricted
]
```

If there are any additional details I can provide, please let me know. Thanks!

**Comment by MHarutunian** [comment]
Thanks @denis256 ,
not sure if I understood you correctly, so just to add some clarification: There are zero references to Azure in my terragrunt configuration or terraform setup. It is only referenced through the SOPS configuration as part of the `sops.azure_kv` setting. And as far as I'm concerned this reference cannot be resolved until `sops_decrypt_file()` is called, more precisely in this line: https://github.com/gruntwork-io/terragrunt/blob/master/config/config_helpers.go#L670

The error messages in this case are coming from SOPS itself I think, the error messages from terragrunt (e.g. `Error in function call`) are not printed. Which might also explain why there aren't any (terragrunt) errors in your example with the nonexisting file.

As an addition to my example, you can test this behavior with any SOPS file that has an entry in `azure_kv`, even if all the values are actually invalid, e.g. like this one
```
foo: you-can-put-anything-here
sops:
  kms: []
  gcp_kms: []
  azure_kv:
    - vault_url: https://you-can-put-anything-here.vault.azure.net
      name: you-can-put-anything-here
      version: you-can-put-anything-here
      created_at: "2022-01-01T00:00:00Z"
      enc: you-can-put-anything-here
  hc_vault: []
  age: []
  lastmodified: "2022-01-01T00:00:00Z"
  mac: null
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
```
Removing the `azure_kv` entry by replacing it with `azure_kv: []` will stop all terragrunt command from printing error messages. But if the entry is there, the ternary will print some errors.
