### ISSUE TITLE
Enhancement Request:  Add a new flag for run-all commands to only display modules

### ISSUE THREAD

**Issue by WolverineFan** [gruntwork-io/terragrunt#2522]
When you execute `run-all` commands they output the list of modules that will be executed in each group, e.g.
```
INFO[0012] The stack at /my/path will be processed in the following order for command apply:
Group 1
- Module /my/path/module1
- Module /my/path/module2

Group 2
- Module /my/path/module3
- Module /my/path/module4
- Module /my/path/module5

Group 3
- Module /my/path/module6
```

Followed by the prompt:
```
Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

I would love to take this output and use it for other purposes.  Terragrunt has already done the hard work of analyzing the dependencies and determining the order of operations, I want to consume that work.

I propose a new flag to `run-all` commands that will just output this information and stop.  The output is already very close to YAML syntax so something like `terragrunt run-all <command> --terragrunt-list-modules-only` that results in the following output:
```yaml
- Group_1:
  - /my/path/module1
  - /my/path/module2
- Group_2:
  - /my/path/module3
  - /my/path/module4
  - /my/path/module5
- Group_3:
  - /my/path/module6
```

If you wanted to get fancy you could allow multiple output formats: `--terragrunt-list-modules-only=[yaml|json|csv|txt]`
