### ISSUE TITLE
I need to use -out feature in terragrunt plan

### ISSUE THREAD

**Issue by 880831ian** [gruntwork-io/terragrunt#2588]
Hello, when I use terraform and gitlab cicd, I use terraform plan -out tfplan to export the content of the plan and save it in the cache. When executing the apply job, use terraform apply -auto-approve tfplan to ensure that the content I see in the apply is consistent with the plan. I checked the terragrunt website and found that there is no similar out function. I would like to ask if there is any other The method can make my gitlab ci have the same content in plan and apply, thank you

Terraform v1.4.6
terragrunt version v0.45.8

<br>

Use cache to save plan output content

```
  cache:
    paths:
      - ${TF_ROOT}/tfplan
```

<br>

```
plan:
  stage: build
  script:
    - terraform plan -out=tfplan
  tags:
    - highcpu

apply:
  stage: deploy
  script:
    - terraform apply -auto-approve tfplan   
  dependencies:
    - plan
  when: manual
```

<br>

The picture attached is that I hope that if the content of the plan is different from the online service when I execute it, the following error will occur, so as to prevent me from forgetting to apply. Others have opened a new pipeline, so I will execute the old apply and let others modify it. The setting is overwritten by me

![image-1685505916477-04-52](https://github.com/gruntwork-io/terragrunt/assets/42373091/6d68d6eb-ef72-402d-b80b-72e46a165183)

**Comment by 880831ian** [comment]
I found it, the original terragrunt -out will be placed under .terragrunt-cache/, I just need to change it to cache .terragrunt-cache/, thank you

```
  cache:
    paths:
      - ${TF_ROOT}/.terragrunt-cache/
```

```
plan:
  stage: build
  script:
    - terragrunt plan -out=tfplan
  tags:
    - highcpu

apply:
  stage: deploy
  script:
    - terragrunt apply tfplan   
  dependencies:
    - plan
  when: manual
```
