### ISSUE TITLE
Passing output from Githubaction to Terragrunt Githubaction

### ISSUE THREAD

**Issue by topeawolwo** [gruntwork-io/terragrunt#2615]
I have an output from a Githubaction defined as

```

 - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            hcls:
              - added|modified: '${{ inputs.working-dir }}/**/terragrunt.hcl'
              - added|modified: '${{ inputs.working-dir }}/**/.terraform.lock.hcl'
      - name: Changed HCL
        if: ${{ steps.filter.outputs.hcls == 'true' }}
        run: |
          echo ${{ steps.filter.outputs.hcls_files }}

```

I want to pass the changed files output from above to Terragrunt

- name: Terragrunt Plan
   
    id: plan
    with:
      run: |
        for dir in ${{ steps.dedupe.outputs.changed_directories }}
        do
          cd ${{github.workspace}}/$dir
          terragrunt plan -no-color
        done
