### ISSUE TITLE
scaffold doesn't show default boilerplate variables

### ISSUE THREAD

**Issue by platymatt** [gruntwork-io/terragrunt#3655]
## Describe the bug

This could be a feature request instead.

If I define default variables in the boilerplate.yml they don't show up in the scaffold output when entering in variables.

When I run `terragrunt scaffold /<module-location>//<module-name>` I get the following output:

![image](https://github.com/user-attachments/assets/a2c39655-f402-4ef9-8220-1d7d607a9df1)

When I run `./boilerplate_linux_amd64 --template-url /module-name/.boilerplate/ --output-folder /output` I get the following output:

![image](https://github.com/user-attachments/assets/a5c27a07-1223-4c17-8b12-0d225af3585f)

I may misunderstand as I thought scaffold was supposed to have similar features to boilerplate, but maybe I don't understand the intent.

## Steps To Reproduce

These steps are using a local module in a monorepo.

1. Create <module-name>/.boilerplate/boilerplate.yml with variables that have defaults
2. Run `terragrunt scaffold <module-location>//<module-name>`
3. Provide variable input

### Example boilerplate.yml used
```yaml
# boilerplate.yml
  - name: Region
    description: The region for where to deploy this infrastucture.
    type: string
    default: us-gov-west-1
  - name: Tenant
    description: The region for where to deploy this infrastucture.
    type: string
    default: common
  - name: Resource
    description: The region for where to deploy this infrastucture.
    type: string
```

## Expected behavior

I expect `terragrunt scaffold` to have similar behavior as `boilerplate` as the usage is similar.

## Versions

- Terragrunt version: terragrunt version v0.56.2
- OpenTofu/Terraform version: Terraform v1.8.1
- Environment details (Ubuntu 20.04, Windows 10, etc.): Running in devcontainer with the following:
```
cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

## Additional context

I am hoping `terragrunt scaffold` to be similar to `boilerplate`, but if that is not the intent then maybe I should use `boilerplate` instead as it has more features.
