### ISSUE TITLE
Terragrunt scaffold should only run hclfmt on updated folders instead of the working directory

### ISSUE THREAD

**Issue by tgeijg** [gruntwork-io/terragrunt#3657]
## Describe the enhancement

Currently when using terragrunt catalog and/or scaffold, the scaffold command runs a `hclfmt` on the working directory. This can subsequently end up touching far more files than just the ones that the scaffold command created. Ideally, the `hclfmt` is either made optional, or only runs against the terragrunt files that scaffold itself generated.

## Additional context

It seems to me that the current assumption is that people would run scaffold from the directory they want to generate terragrunt files in. Given that assumption the idea of running the `hclfmt` on the working directory isn't a terrible one. However, terragrunt's own [architecture proposal is to use a base/child structure](https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/#using-include-to-dry-common-terragrunt-config). The easiest way I've found to have scaffold generate both a base and a child terragrunt file, is by running scaffold from the root of the repo (and have the user input the file paths for both directories). This is reasonably easy to achieve using boilerplate dependencies. 

The biggest problem I'm facing is that running the terragrunt scaffold from the root of the directory will run the `hclfmt` against the entire repo, instead of just the two (or more) subfolders that the command itself created.

## Example

The below boilerplate template essentially just created two dependencies in two folders, the path of which is required as user input.
```yaml
variables:
  - name: sourceUrl
    description: Url for source module
    type: string
    default: ""

  - name: requiredVariables
    description: Required input variables for module
    type: list
    default: []

  - name: optionalVariables
    description: Optional input variables for module
    type: list
    default: []

  - name: baseFileName
    description: Name for the base terragrunt file WITHOUT file extension, e.g. "dynamodb". (NOT "terragrunt")
    type: string
    validations:
      - required
      - length-3-50

  - name: baseFilePath
    description: |-
      Path for the base file, e.g. "base/team/service/"
      DO NOT add a leading slash, DO add a trailing slash 
    type: string
    validations:
      - required
      - length-5-500

  - name: leafFilePath
    description: |-
      Path for the leaf file, e.g. "development/us-east-1/team/service/"
      DO NOT add a leading slash, DO add a trailing slash 
    type: string
    validations:
      - required
      - length-5-500

partials:
  - ../.boilerplate-files/boilerplate-partials/*.hcl

dependencies:
  - name: base
    template-url: ../.boilerplate-files/base-file
    output-folder: "{{ .baseFilePath }}"
  
  - name: leaf
    template-url: ../.boilerplate-files/leaf-file
    output-folder: "{{ .leafFilePath }}"
```
(dependency templates not included for brevity)

Technically you can run this from anywhere in the repo, but the most logical place to run the scaffold command for the above boilerplate template is the root of the repo. All files generated will be in subfolders, so running hclfmt against the entire working directory is not ideal, as it may touch a whole list of files which are not in any way related to the scaffold call.
