### ISSUE TITLE
Add support for for_each block in stacks 

### ISSUE THREAD

**Issue by sourava01** [gruntwork-io/terragrunt#4350]
## Describe the enhancement

Being able to conditionally disable a unit allows for a more flexibility for defining resources across multiple environments. This will help make nested stacks truly dynamic. 

Consider a case where nested stacks are used to define different environments. Since there is no such functionality right now, I have to either define different versions of `terragrunt.stack.hcl` across multiple environments. Or, handle it inside my terraform or terragrunt file to not provision the resource. 
In the first case, I am repeating myself, breaking the DRY code.
In the second case, I have a useless file in my stacks folder. If we use `hidden = false` this becomes  misleading and confusing.

## Additional context

Example of how this can be achieved

```
# production/terragrunt.stack.hcl

locals {
  env = "prod"
  external_lb = true
}

stack "load_balancers" {
  source = "../load_balancers"
  path = "load_balancers"
  values = {
    external_lb = local.external_lb
    env = local.env
  }
}


# dev/terragrunt.stack.hcl

locals {
  env = "dev"
  external_lb = false
}

stack "load_balancers" {
  source = "../load_balancers"
  path = "load_balancers"
  values = {
    external_lb = local.external_lb
    env = local.env
  }
}


# load_balancers/terragrunt.stack.hcl

unit "external_lb" {
  disable = !stack.values.external_lb
  source = "github.com/acme/terragrunt-units.git//units/alb?ref=v1.2.3"
  path   = "external_lb"
  values = {
    environment = stack.values.env
  }
}

unit "internal_lb" {
  source = "github.com/acme/terragrunt-units.git//units/alb?ref=v1.2.3"
  path   = "internal_lb"
  values = {
    environment = stack.values.env
  }
}

```

**Comment by sourava01** [comment]
Hi @yhakbar 
Exclude block does cover some of the functionalities I am looking for, but there are features which is not included in it. Expanding on the example I mentioned above, consider a usecase where a user wants to disable a complete stack based on some criteria. Right now the only option is to use an `exclude` statement in every `terragrunt.hcl` and pass `disable = true` as an input value to all the `terragrunt.hcl` files. Definitely not the best way to achieve this. Especially if you plan to preserve the `terragrunt.hcl` files generated by the stack, then you will have multiple unnecessary files just sitting around.

A better way of achieving this could be by introducing a `for_each` block for the `stack` and `unit` block. Thoughts?

**Comment by sourava01** [comment]
hi @yhakbar can you let me know if there is any plans to support this? I have a usecase where I have to loop over a list to generate multiple stack units. If this is in the roadmap I can wait, otherwise I will have to build a wrapper around the existing stacks feature to support this.

**Comment by yhakbar** [comment]
Hey @sourava01 ,

There are no plans to support this in the short term. I'd recommend spinning up your own solution, and sharing it here so that other folks can collaborate with you on stop gap solutions until we can offer a first class feature for this.

**Comment by radkawar** [comment]
@sourava01 (and other folk who seek a solution, until a verdict is made on #4504) is to use boilerplate to generate the `terragrunt.stack.hcl`.

for a very contrived (and simple) example of my current workflow:

1. single `vars.yml` to define all the inputs for the stacks
2. an orchestrator template to generate all templates with one command
3. individual templates for each stack

```
boilerplate --template-url ./template/orchestrator --output-folder . --non-interactive --var-file var.yml
```



```
// template/link/terragrunt.stack.hcl
{{- range .Platforms}}

unit "link_{{.account_id}}" {
  source = "${local.units_path}/foundation/aws-link"
  path   = "./link_{{.account_id}}"
}
{{- end}}
```

```
# template/link/boilerplate.yml
variables:
  - name: Platforms
    type: list

skip_files:
  - path: "*.yml"
  - path: "*.yaml"
  - path: "boilerplate.yml"

hooks:
  after:
    - command: terragrunt
      args:
        - hcl
        - fmt
        - --file
        - "{{ outputFolder }}/terragrunt.stack.hcl"
```


And then you can "orchestrate" multiple stack generations with boilerplate again

```
# template/orchestrator/boilerplate.yml
variables:
  - name: Platforms
    type: list

skip_files:
  - path: "**/*"

dependencies:
  - name: link
    template-url: ../link
    output-folder: ./link
```

```
# vars.yml
Platforms:
  - account_id: "000000000000"
```
